# Generated by Django 3.1 on 2020-08-15 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('idno', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('description', models.CharField(max_length=5000)),
                ('photo', models.ImageField(upload_to='product_images/')),
                ('pdate', models.DateField(auto_now_add=True)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('contactno', models.IntegerField(unique=True)),
                ('gender', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('status', models.CharField(default=None, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProductsSales',
            fields=[
                ('idno', models.AutoField(primary_key=True, serialize=False)),
                ('qty', models.IntegerField()),
                ('total_bill', models.FloatField()),
                ('purchase_date', models.DateField(auto_now_add=True)),
                ('product_id', models.ManyToManyField(to='e_mall.Products')),
                ('user_id', models.ManyToManyField(to='e_mall.Users')),
            ],
        ),
    ]
